-- 1. The Atomic Unit: A Single Screen/Page
create table components (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,                -- e.g., "Uber Login Screen"
  description text,
  code_string text not null,         -- The raw React component code
  tags text[],                       -- e.g., ['auth', 'mobile', 'dark-mode']
  original_app text                  -- e.g., "Uber"
);

-- 2. The Container: A User Journey
create table flows (
  id bigint generated by default as identity primary key,
  name text not null,                -- e.g., "Uber Driver Onboarding"
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. The Link: Connecting Flows to Components
create table flow_steps (
  id bigint generated by default as identity primary key,
  flow_id bigint references flows(id) on delete cascade,
  component_id bigint references components(id) on delete cascade,
  step_order int not null,           -- 1, 2, 3 (Defines the sequence)
  unique(flow_id, step_order)        -- Prevent duplicate steps at same index
);
