-- Seeding filter_definitions
INSERT INTO filter_definitions (section, group_name, name, slug)
VALUES
('category', NULL, 'AI', 'ai'),
('category', NULL, 'Business', 'business'),
('category', NULL, 'Collaboration', 'collaboration'),
('category', NULL, 'Communication', 'communication'),
('category', NULL, 'CRM', 'crm'),
('category', NULL, 'Crypto & Web3', 'crypto-web3'),
('category', NULL, 'Developer Tools', 'developer-tools'),
('category', NULL, 'Education', 'education'),
('category', NULL, 'Entertainment', 'entertainment'),
('category', NULL, 'Finance', 'finance'),
('category', NULL, 'Food & Drink', 'food-drink'),
('category', NULL, 'Graphics & Design', 'graphics-design'),
('category', NULL, 'Health & Fitness', 'health-fitness'),
('category', NULL, 'Jobs & Recruitment', 'jobs-recruitment'),
('category', NULL, 'Lifestyle', 'lifestyle'),
('category', NULL, 'Medical', 'medical'),
('category', NULL, 'Music & Audio', 'music-audio'),
('category', NULL, 'Maps & Navigation', 'maps-navigation'),
('category', NULL, 'News', 'news'),
('category', NULL, 'Photo & Video', 'photo-video'),
('category', NULL, 'Productivity', 'productivity'),
('category', NULL, 'Real Estate', 'real-estate'),
('category', NULL, 'Reference', 'reference'),
('category', NULL, 'Shopping', 'shopping'),
('category', NULL, 'Social Networking', 'social-networking'),
('category', NULL, 'Sports', 'sports'),
('category', NULL, 'Travel & Transportation', 'travel-transportation'),
('category', NULL, 'Utilities', 'utilities'),
('screen', 'New User Experience', 'Account Setup', 'account-setup'),
('screen', 'New User Experience', 'Guided Tour & Tutorial', 'guided-tour-tutorial'),
('screen', 'New User Experience', 'Signup', 'signup'),
('screen', 'New User Experience', 'Verification', 'verification'),
('screen', 'Account Management', 'Delete & Deactivate Account', 'delete-deactivate-account'),
('screen', 'Account Management', 'Forgot Password', 'forgot-password'),
('screen', 'Account Management', 'Login', 'login'),
('screen', 'Account Management', 'My Account & Profile', 'my-account-profile'),
('screen', 'Account Management', 'Settings & Preferences', 'settings-preferences'),
('screen', 'Communication', 'Acknowledgement & Success', 'acknowledgement-success'),
('screen', 'Communication', 'Action Option', 'action-option'),
('screen', 'Communication', 'Confirmation', 'confirmation'),
('screen', 'Communication', 'Empty State', 'empty-state'),
('screen', 'Communication', 'Error', 'error'),
('screen', 'Communication', 'Feature Info', 'feature-info'),
('screen', 'Communication', 'Feedback', 'feedback'),
('screen', 'Communication', 'Help & Support', 'help-support'),
('screen', 'Communication', 'Loading', 'loading'),
('screen', 'Communication', 'Permission', 'permission'),
('screen', 'Communication', 'Suggestions & Similar Items', 'suggestions-similar-items'),
('screen', 'Commerce & Finance', 'Billing', 'billing'),
('screen', 'Commerce & Finance', 'Cart & Bag', 'cart-bag'),
('screen', 'Commerce & Finance', 'Checkout', 'checkout'),
('screen', 'Commerce & Finance', 'Order Confirmation', 'order-confirmation'),
('screen', 'Commerce & Finance', 'Order Detail', 'order-detail'),
('screen', 'Commerce & Finance', 'Order History', 'order-history'),
('screen', 'Commerce & Finance', 'Payment Method', 'payment-method'),
('screen', 'Commerce & Finance', 'Pricing', 'pricing'),
('screen', 'Commerce & Finance', 'Promotions & Rewards', 'promotions-rewards'),
('screen', 'Commerce & Finance', 'Shop & Storefront', 'shop-storefront'),
('screen', 'Commerce & Finance', 'Subscription & Paywall', 'subscription-paywall'),
('screen', 'Commerce & Finance', 'Wallet & Balance', 'wallet-balance'),
('screen', 'Social', 'Achievements & Awards', 'achievements-awards'),
('screen', 'Social', 'Chat Detail', 'chat-detail'),
('screen', 'Social', 'Comments', 'comments'),
('screen', 'Social', 'Followers & Following', 'followers-following'),
('screen', 'Social', 'Invite Teammates', 'invite-teammates'),
('screen', 'Social', 'Leaderboard', 'leaderboard'),
('screen', 'Social', 'Notifications', 'notifications'),
('screen', 'Social', 'Reviews & Ratings', 'reviews-ratings'),
('screen', 'Social', 'Social Feed', 'social-feed'),
('screen', 'Social', 'User / Group Profile', 'user---group-profile'),
('screen', 'Content', 'Article Detail', 'article-detail'),
('screen', 'Content', 'Browse & Discover', 'browse-discover'),
('screen', 'Content', 'Class & Lesson Detail', 'class-lesson-detail'),
('screen', 'Content', 'Code Editor', 'code-editor'),
('screen', 'Content', 'Emails & Messages', 'emails-messages'),
('screen', 'Content', 'Event Detail', 'event-detail'),
('screen', 'Content', 'Goal & Task', 'goal-task'),
('screen', 'Content', 'Home', 'home'),
('screen', 'Content', 'News Feed', 'news-feed'),
('screen', 'Content', 'Note Detail', 'note-detail'),
('screen', 'Content', 'Other Content', 'other-content'),
('screen', 'Content', 'Post Detail', 'post-detail'),
('screen', 'Content', 'Product Detail', 'product-detail'),
('screen', 'Content', 'Quiz', 'quiz'),
('screen', 'Content', 'Recipe Detail', 'recipe-detail'),
('screen', 'Content', 'Song & Podcast Detail', 'song-podcast-detail'),
('screen', 'Content', 'Stories', 'stories'),
('screen', 'Content', 'TV Show & Movie Detail', 'tv-show-movie-detail'),
('screen', 'Actions', 'Add & Create', 'add-create'),
('screen', 'Actions', 'Ban & Block', 'ban-block'),
('screen', 'Actions', 'Cancel', 'cancel'),
('screen', 'Actions', 'Delete', 'delete'),
('screen', 'Actions', 'Draw & Annotate', 'draw-annotate'),
('screen', 'Actions', 'Edit', 'edit'),
('screen', 'Actions', 'Favorite & Pin', 'favorite-pin'),
('screen', 'Actions', 'Filter & Sort', 'filter-sort'),
('screen', 'Actions', 'Flag & Report', 'flag-report'),
('screen', 'Actions', 'Follow & Subscribe', 'follow-subscribe'),
('screen', 'Actions', 'Import & Export', 'import-export'),
('screen', 'Actions', 'Invite & Refer Friends', 'invite-refer-friends'),
('screen', 'Actions', 'Like & Upvote', 'like-upvote'),
('screen', 'Actions', 'Move', 'move'),
('screen', 'Actions', 'Other Action', 'other-action'),
('screen', 'Actions', 'Publish', 'publish'),
('screen', 'Actions', 'Reorder', 'reorder'),
('screen', 'Actions', 'Save', 'save'),
('screen', 'Actions', 'Schedule', 'schedule'),
('screen', 'Actions', 'Search', 'search'),
('screen', 'Actions', 'Select', 'select'),
('screen', 'Actions', 'Set', 'set'),
('screen', 'Actions', 'Share', 'share'),
('screen', 'Actions', 'Transfer & Send Money', 'transfer-send-money'),
('screen', 'Actions', 'Upload & Download', 'upload-download'),
('screen', 'Data', 'Charts', 'charts'),
('screen', 'Data', 'Dashboard', 'dashboard'),
('screen', 'Data', 'Progress', 'progress'),
('screen', 'User Collections', 'Bookmarks & Collections', 'bookmarks-collections'),
('screen', 'User Collections', 'Playlists', 'playlists'),
('screen', 'User Collections', 'Trash & Archive', 'trash-archive'),
('screen', 'Utility', 'Audio Player', 'audio-player'),
('screen', 'Utility', 'Audio & Video Recorder', 'audio-video-recorder'),
('screen', 'Utility', 'Calendar', 'calendar'),
('screen', 'Utility', 'Call', 'call'),
('screen', 'Utility', 'Canvas', 'canvas'),
('screen', 'Utility', 'Chat Bot', 'chat-bot'),
('screen', 'Utility', 'Command Palette', 'command-palette'),
('screen', 'Utility', 'Date & Time', 'date-time'),
('screen', 'Utility', 'Map', 'map'),
('screen', 'Utility', 'Media Editor', 'media-editor'),
('screen', 'Utility', 'QR Code', 'qr-code'),
('screen', 'Utility', 'Timeline & History', 'timeline-history'),
('screen', 'Utility', 'Timer & Clock', 'timer-clock'),
('screen', 'Utility', 'Video Player', 'video-player'),
('screen', 'Misc', 'Dark Mode', 'dark-mode'),
('screen', 'Misc', 'Internal Tool', 'internal-tool'),
('screen', 'Misc', 'Misc', 'misc'),
('screen', 'Layouts', 'Kanban Board', 'kanban-board'),
('screen', 'Layouts', 'Multi-Column Layout', 'multi-column-layout'),
('ui_element', 'Control', 'Accordion', 'accordion'),
('ui_element', 'Control', 'Breadcrumbs', 'breadcrumbs'),
('ui_element', 'Control', 'Button', 'button'),
('ui_element', 'Control', 'Checkbox', 'checkbox'),
('ui_element', 'Control', 'Color Picker', 'color-picker'),
('ui_element', 'Control', 'Combobox', 'combobox'),
('ui_element', 'Control', 'Date Picker', 'date-picker'),
('ui_element', 'Control', 'Editable Text', 'editable-text'),
('ui_element', 'Control', 'File Upload', 'file-upload'),
('ui_element', 'Control', 'Floating Action Button', 'floating-action-button'),
('ui_element', 'Control', 'Link', 'link'),
('ui_element', 'Control', 'Pagination', 'pagination'),
('ui_element', 'Control', 'Radio Button', 'radio-button'),
('ui_element', 'Control', 'Rating Control', 'rating-control'),
('ui_element', 'Control', 'Search Bar', 'search-bar'),
('ui_element', 'Control', 'Segmented Control', 'segmented-control'),
('ui_element', 'Control', 'Select', 'select'),
('ui_element', 'Control', 'Slider', 'slider'),
('ui_element', 'Control', 'Stepper', 'stepper'),
('ui_element', 'Control', 'Switch', 'switch'),
('ui_element', 'Control', 'Tab', 'tab'),
('ui_element', 'Control', 'Text Field', 'text-field'),
('ui_element', 'Control', 'Tile', 'tile'),
('ui_element', 'Control', 'Time Picker', 'time-picker'),
('ui_element', 'View', 'Badge', 'badge'),
('ui_element', 'View', 'Banner', 'banner'),
('ui_element', 'View', 'Card', 'card'),
('ui_element', 'View', 'Carousel', 'carousel'),
('ui_element', 'View', 'Chip', 'chip'),
('ui_element', 'View', 'Divider', 'divider'),
('ui_element', 'View', 'Gallery', 'gallery'),
('ui_element', 'View', 'Grid List', 'grid-list'),
('ui_element', 'View', 'Keyboard Key', 'keyboard-key'),
('ui_element', 'View', 'Loading Indicator', 'loading-indicator'),
('ui_element', 'View', 'Map Pin', 'map-pin'),
('ui_element', 'View', 'Progress Indicator', 'progress-indicator'),
('ui_element', 'View', 'Side Navigation', 'side-navigation'),
('ui_element', 'View', 'Skeleton', 'skeleton'),
('ui_element', 'View', 'Stacked List', 'stacked-list'),
('ui_element', 'View', 'Status Dot', 'status-dot'),
('ui_element', 'View', 'Table', 'table'),
('ui_element', 'View', 'Table of Contents', 'table-of-contents'),
('ui_element', 'View', 'Toolbar', 'toolbar'),
('ui_element', 'View', 'Top Navigation Bar', 'top-navigation-bar'),
('ui_element', 'View', 'Tree', 'tree'),
('ui_element', 'Overlay', 'Coach Marks', 'coach-marks'),
('ui_element', 'Overlay', 'Context Menu', 'context-menu'),
('ui_element', 'Overlay', 'Dialog', 'dialog'),
('ui_element', 'Overlay', 'Drawer', 'drawer'),
('ui_element', 'Overlay', 'Dropdown Menu', 'dropdown-menu'),
('ui_element', 'Overlay', 'Full-Screen Overlay', 'full-screen-overlay'),
('ui_element', 'Overlay', 'Navigation Menu', 'navigation-menu'),
('ui_element', 'Overlay', 'Popover', 'popover'),
('ui_element', 'Overlay', 'Toast', 'toast'),
('ui_element', 'Overlay', 'Tooltip', 'tooltip'),
('ui_element', 'Imagery', 'Avatar', 'avatar'),
('ui_element', 'Imagery', 'Icon', 'icon'),
('ui_element', 'Imagery', 'Illustration', 'illustration'),
('ui_element', 'Imagery', 'Logo', 'logo'),
('ui_element', 'Imagery', 'Photo', 'photo'),
('flow', 'New User Experience', 'Browsing Tutorial', 'browsing-tutorial'),
('flow', 'New User Experience', 'Creating Account', 'creating-account'),
('flow', 'New User Experience', 'Onboarding', 'onboarding'),
('flow', 'Account Management', 'Editing Profile', 'editing-profile'),
('flow', 'Account Management', 'Deleting & Deactivating Account', 'deleting-deactivating-account'),
('flow', 'Account Management', 'Logging In', 'logging-in'),
('flow', 'Account Management', 'Logging Out', 'logging-out'),
('flow', 'Account Management', 'Resetting Password', 'resetting-password'),
('flow', 'Account Management', 'Switching Account', 'switching-account'),
('flow', 'Commerce & Finance', 'Adding to Cart & Bag', 'adding-to-cart-bag'),
('flow', 'Commerce & Finance', 'Booking & Reserving', 'booking-reserving'),
('flow', 'Commerce & Finance', 'Canceling Order & Refunding', 'canceling-order-refunding'),
('flow', 'Commerce & Finance', 'Canceling Subscription', 'canceling-subscription'),
('flow', 'Commerce & Finance', 'Listing', 'listing'),
('flow', 'Commerce & Finance', 'Purchasing & Ordering', 'purchasing-ordering'),
('flow', 'Commerce & Finance', 'Redeeming', 'redeeming'),
('flow', 'Commerce & Finance', 'Subscribing & Upgrading', 'subscribing-upgrading'),
('flow', 'Commerce & Finance', 'Transferring Money & Donating', 'transferring-money-donating'),
('flow', 'Social', 'Banning & Blocking', 'banning-blocking'),
('flow', 'Social', 'Calling', 'calling'),
('flow', 'Social', 'Chatting & Sending Messages', 'chatting-sending-messages'),
('flow', 'Social', 'Commenting & Replying', 'commenting-replying'),
('flow', 'Social', 'Following & Subscribing', 'following-subscribing'),
('flow', 'Social', 'Gifting', 'gifting'),
('flow', 'Social', 'Giving Feedback', 'giving-feedback'),
('flow', 'Social', 'Inviting Teammates & Friends', 'inviting-teammates-friends'),
('flow', 'Social', 'Joining & Accepting', 'joining-accepting'),
('flow', 'Social', 'Leaving', 'leaving'),
('flow', 'Social', 'Liking & Upvoting', 'liking-upvoting'),
('flow', 'Social', 'Muting', 'muting'),
('flow', 'Social', 'Referring Friends', 'referring-friends'),
('flow', 'Social', 'Registering', 'registering'),
('flow', 'Social', 'Reporting', 'reporting'),
('flow', 'Social', 'Requesting', 'requesting'),
('flow', 'Social', 'Reviewing & Rating', 'reviewing-rating'),
('flow', 'Social', 'Scheduling', 'scheduling'),
('flow', 'Social', 'Sharing', 'sharing'),
('flow', 'Content', 'Adding & Creating', 'adding-creating'),
('flow', 'Content', 'Archiving', 'archiving'),
('flow', 'Content', 'Copying & Duplicating', 'copying-duplicating'),
('flow', 'Content', 'Deleting & Removing', 'deleting-removing'),
('flow', 'Content', 'Drawing', 'drawing'),
('flow', 'Content', 'Editing & Updating', 'editing-updating'),
('flow', 'Content', 'Favoriting & Pinning', 'favoriting-pinning'),
('flow', 'Content', 'Filtering & Sorting', 'filtering-sorting'),
('flow', 'Content', 'Importing & Exporting', 'importing-exporting'),
('flow', 'Content', 'Listening to Audio', 'listening-to-audio'),
('flow', 'Content', 'Logging & Tracking', 'logging-tracking'),
('flow', 'Content', 'Marking', 'marking'),
('flow', 'Content', 'Moving', 'moving')
ON CONFLICT (slug) DO NOTHING;
