-- Drop existing tables to allow a clean reset
drop table if exists flow_steps cascade;
drop table if exists flows cascade;
drop table if exists components cascade;
drop table if exists profiles cascade;

-- Create a table for public profiles (linked to auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- 1. The Atomic Unit: A Single Screen/Page
create table components (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  code_string text not null,
  tags text[],
  original_app text
);

-- 2. The Container: A User Journey
create table flows (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. The Link: Connecting Flows to Components
create table flow_steps (
  id bigint generated by default as identity primary key,
  flow_id bigint references flows(id) on delete cascade,
  component_id bigint references components(id) on delete cascade,
  step_order int not null,
  unique(flow_id, step_order)
);

-- Enable RLS on Data Tables
alter table components enable row level security;
alter table flows enable row level security;
alter table flow_steps enable row level security;

-- Policies for Components
create policy "Components are viewable by authenticated users" on components
  for select using (auth.role() = 'authenticated');

create policy "Components are insertable by admins only" on components
  for insert with check (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "Components are updatable by admins only" on components
  for update using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

-- Policies for Flows
create policy "Flows are viewable by authenticated users" on flows
  for select using (auth.role() = 'authenticated');

create policy "Flows are insertable by admins only" on flows
  for insert with check (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

-- Policies for Flow Steps
create policy "Flow Steps are viewable by authenticated users" on flow_steps
  for select using (auth.role() = 'authenticated');

create policy "Flow Steps are insertable by admins only" on flow_steps
  for insert with check (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
